apiVersion: v1
kind: ConfigMap
metadata:
  name: vault-conf
data:
  vault.hcl: |

    ui = "true"
    cluster_name = "dc1"

    storage "consul" {
      address = "consul:8500"
      path    = "vault/"
      ha_enabled = "true"
    }

    listener "tcp" {
      address     = "0.0.0.0:8200"
      tls_disable = "true"
    }
