version: "3.3"
services:
  mongodb_server:
    image: mongo:4.4
    command: mongod --serviceExecutor adaptive
    ports:
      - 27017:27017
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin_user
      - MONGO_INITDB_ROOT_PASSWORD=admin_pass
      - MONGO_INITDB_DATABASE=application_database
    volumes:
      - mongodb_server_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js
volumes:
  mongodb_server_data:
