version: "3.3"

services:
  primary:
    hostname: 'primary'
    image: crunchydata/crunchy-postgres:centos7-11.8-4.3.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=primary
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
      - PG_PRIMARY_PORT=5432
    volumes:
      - pg-primary-vol:/pgdata
    ports:
      - "5432:5432"
    networks:
      - net-postgres
    deploy:
      placement:
        constraints:
          - node.labels.type == primary
          - node.role == worker
  replica:
    image: crunchydata/crunchy-postgres:centos7-11.8-4.3.2
    environment:
      - PGHOST=/tmp
      - MAX_CONNECTIONS=10
      - MAX_WAL_SENDERS=5
      - PG_MODE=replica
      - PG_PRIMARY_HOST=primary
      - PG_PRIMARY_PORT=5432
      - PG_PRIMARY_USER=primaryuser
      - PG_PRIMARY_PASSWORD=password
      - PG_DATABASE=testdb
      - PG_USER=testuser
      - PG_PASSWORD=password
      - PG_ROOT_PASSWORD=password
    volumes:
      - pg-replica-vol:/pgdata
    ports:
      - "5433:5432"
    networks:
      - net-postgres
    deploy:
      placement:
        constraints:
          - node.labels.type != primary
          - node.role == worker
networks:
  net-postgres:

volumes:
  pg-primary-vol:
  pg-replica-vol:
#https://github.com/CrunchyData/crunchy-containers/blob/master/examples/docker/swarm-service/docker-compose.yml
#
#docker run --name 194-restore -e MODE=RESTORE -e RESTORE_DIR=/home/mysql_backups/6-161/export-20210203-033002/ -e DB_HOST=192.168.6.162 -e DB_PORT=3306 -e DB_PASS=root -v /home/mysql_backups/194:/backup davidche/mysql-backup:latest
#docker run --name 161-restore --rm -e MODE=RESTORE -e DB_HOST=192.168.6.162 -e DB_PORT=3306 -e DB_PASS=CQY@mass2019 -e RESTORE_DIR=/backup/test/ -e DB_NAME=trade_center -v /home/mysql_backups/6-161:/backup 192.168.9.10:5000/mysql-backup:latest
#docker run --name 161-restore --rm -e MODE=RESTORE -e DB_HOST=192.168.6.162 -e DB_PORT=3306 -e DB_PASS=CQY@mass2019 -e RESTORE_DIR=/backup/test/ -v /home/mysql_backups/6-161:/backup 192.168.9.10:5000/mysql-backup:latest

