version: '3'

services:
  redis-master:
    hostname: redis-master
    image: 'bitnami/redis:5.0.5'
    ports:
      - '6379:6379'
    environment:
      - REDIS_REPLICATION_MODE=master
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'r_data:/bitnami/redis/data'
    command: /run.sh --maxmemory 512mb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.db-node == true]  # 部署标签约束

  redis-replica:
    image: 'bitnami/redis:5.0.5'
    ports:
      - '36379:6379'
    depends_on:
      - redis-master
    environment:
      - REDIS_REPLICATION_MODE=slave
      - REDIS_MASTER_HOST=redis-master
      - REDIS_MASTER_PORT_NUMBER=6379
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'b_data:/bitnami/redis/data'
    command: /run.sh --maxmemory 512mb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.db-node == true]  # 部署标签约束

# redis commander ui tools
  redis-commander:
    hostname: redis-commander
    image: rediscommander/redis-commander:latest
    restart: always
    environment:
    - REDIS_HOSTS=local:redis-master:6379
    ports:
    - "8081:8081"
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.db-node == true]  # 部署标签约束

volumes:
  r_data:
  b_data: