version: "3.1"
services:
  redis-master-1:
    image: redis:5
    ports:
      - "7000:7000"
    networks:
      redisnet:
        ipv4_address: 10.0.0.2
    command: sh -c "redis-server --port 7000 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000"

  redis-master-2:
    image: redis:5
    networks:
      redisnet:
        ipv4_address: 10.0.0.3
    depends_on:
      - redis-master-1
    command: sh -c "redis-server --port 7001 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000"

  redis-master-3:
    image: redis:5
    command: sh -c "redis-server --port 7002 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000"
    networks:
      redisnet:
        ipv4_address: 10.0.0.4
    depends_on:
      - redis-master-2

  redis-slave-1:
    image: redis:5
    command: sh -c "redis-server --port 7003 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000"
    networks:
      redisnet:
        ipv4_address: 10.0.0.5
    depends_on:
      - redis-master-1

  redis-slave-2:
    image: redis:5
    command: sh -c "redis-server --port 7004 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000"
    networks:
      redisnet:
        ipv4_address: 10.0.0.6
    depends_on:
      - redis-master-2

  redis-slave-3:
    image: redis:5
    command: sh -c "redis-server --port 7005 --cluster-enabled yes --cluster-require-full-coverage no --cluster-config-file nodes.conf --notify-keyspace-events Kx --cluster-node-timeout 15000 --daemonize yes && yes yes | redis-cli -p 7005 --cluster create --cluster-replicas 1 10.0.0.2:7000 10.0.0.3:7001 10.0.0.4:7002 10.0.0.5:7003 10.0.0.6:7004 10.0.0.7:7005 && tail -f /dev/null"
    networks:
      redisnet:
        ipv4_address: 10.0.0.7
    depends_on:
      - redis-master-3
networks:
  redisnet:
    driver: bridge
    ipam:
      config:
        - subnet: 10.0.0.0/8
#https://gist.github.com/debugmaster/e38759cc42f809cc5e4241840eba4e64
