version: '3'

services:
  redis-master:
    hostname: redis-master
    image: 'bitnami/redis:6.0.4'
    ports:
      - '6379:6379'
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'r_data:/bitnami/redis/data'
    command: /run.sh --maxmemory 4064mb
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.redis-node == true]  # 部署标签约束
    networks:
      - redis
      - prod
      
volumes:
  r_data:

networks:
  redis:
  prod:
    external: true