version: '3'

services:
  mariadb-master:
    image: 'bitnami/mariadb:10.2.23'
    ports:
      - '3306'
    volumes:
      - 'mariadb_master_data:/bitnami/mariadb'
    environment:
      - MARIADB_REPLICATION_MODE=master
      - MARIADB_REPLICATION_USER=repl_user
      #- MARIADB_REPLICATION_PASSWORD=repl_user_password
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      #- MARIADB_PASSWORD=my_password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
      - MARIADB_ROOT_PASSWORD=my_root_password
      - MARIADB_EXTRA_FLAGS=--max-connect-errors=1000 --max_connections=155

  mariadb-slave:
    image: 'bitnami/mariadb:10.2.23'
    ports:
      - '3306'
    depends_on:
      - mariadb-master
    environment:
      - MARIADB_REPLICATION_MODE=slave
      - MARIADB_REPLICATION_USER=repl_user
      #- MARIADB_REPLICATION_PASSWORD=repl_user_password      
      - MARIADB_USER=my_user
      - MARIADB_DATABASE=my_database
      #- MARIADB_PASSWORD=my_password
      - MARIADB_MASTER_HOST=mariadb-master
      - MARIADB_MASTER_PORT_NUMBER=3306
      - MARIADB_MASTER_ROOT_PASSWORD=my_root_password
      # ALLOW_EMPTY_PASSWORD is recommended only for development.
      - ALLOW_EMPTY_PASSWORD=yes
    volumes:
      - 'mariadb_slave_data:/bitnami/mariadb'

volumes:
  mariadb_master_data:
    driver: local
  mariadb_slave_data:
    driver: local