version: '3'

services:
  postgresql-master:
    image: 'bitnami/postgresql:11.2.0'
    ports:
      - '5432:5432'
    volumes:
      - 'postgresql_master_data:/bitnami'
    environment:
      - POSTGRESQL_REPLICATION_MODE=master
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_USERNAME=my_user
      - POSTGRESQL_PASSWORD=my_password
      - POSTGRESQL_DATABASE=my_database

  postgresql-slave:
    image: 'bitnami/postgresql:11.2.0'
    ports:
      - '15432:5432'
    depends_on:
      - postgresql-master
    environment:
      - POSTGRESQL_REPLICATION_MODE=slave
      - POSTGRESQL_REPLICATION_USER=repl_user
      - POSTGRESQL_REPLICATION_PASSWORD=repl_password
      - POSTGRESQL_MASTER_HOST=postgresql-master
      - POSTGRESQL_MASTER_PORT_NUMBER=5432
    volumes:
      - 'postgresql_slave_data:/bitnami'
volumes:
  postgresql_master_data:
    driver: local
  postgresql_slave_data:
    driver: local