version: '3.3'

services:
  server:
    image: dockercloud/haproxy
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - proxy_certs:/certs:ro
    ports:
      - target: 80
        published: 80
        protocol: tcp
        mode: host
      - target: 443
        published: 443
        protocol: tcp
        mode: host
    networks:
      - rproxy
    environment:
     - TZ=America/Argentina/Buenos_Aires
     - TIMEOUT=connect 50000, client 50000, server 50000
     - CERT_FOLDER="/certs/"
     - RSYSLOG_DESTINATION=10.1.1.242
    deploy:
      mode: replicated
      replicas: 3
      placement:
        constraints: [node.role == manager]
      restart_policy:
       condition: on-failure
       max_attempts: 3
       window: 120s
networks:
  rproxy:
    external:
      name: reverse_proxy