kind: pipeline
name: hello-pipeline
type: docker
#Author:David.che

steps:
  - name: restore-cache
    image: drillster/drone-volume-cache
    volumes:
      - name: cache
        path: /cache
    settings:
      restore: true
      mount:
        - ./.m2

# cache   192.168.9.10:5000/maven:3-jdk-8
  - name: say-hello
    image: busybox
    commands:
      - echo hello-world
    when:
      branch:
        - master
      event:
        - push
# build
  - name: build
    image: 192.168.9.10:5000/maven:3-jdk-8
    commands:
#      - mvn install -DskipTests=true -Dmaven.repo.local=/.m2/repository -Dmaven.javadoc.skip=true -B -V
      - mvn install -DskipTests=true -Dmaven.repo.local=./.m2/repository -Dmaven.javadoc.skip=true -B -V
#    volumes:
#       - name: cache2
#         path: /.m2
#    
    when:
      branch:
        - master
      event:
        - push

#        package
#
  - name: rebuild-cache
    image: drillster/drone-volume-cache
    settings:
      rebuild: true
      mount:
        - ./.m2
    volumes:
    - name: cache
      path: /cache
#
volumes:
  - name: cache
    host:
      path: /tmp/cache
  - name: cache2
    host:
      path: /tmp/cache2