version: '3'
services:
  helloworld:
    image: tutum/hello-world:latest
    networks:
     - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.demo_helloworld.rule=PathPrefix(`/demo`)"
    #    - "traefik.http.routers.helloworld.rule=Host(`helloworld.local`)"
        - "traefik.http.routers.demo_helloworld.entrypoints=web"
        - "traefik.http.services.demo_helloworld.loadbalancer.server.port=80"
networks:
  traefik-public:
    external: true                                                                                         