version: '3'

#zeebe, kafka, postgre docker-compose

volumes:
  sample_zeebe_data:
  sample_zk_data:
  sample_zk_txn_logs:
  sample_kafka_data:

networks:
  sample_network:
    driver: bridge

services:
  db:
    container_name: sample_db
    image: postgres:13.3
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: secret

  zookeeper:
    container_name: sample_zk
    image: confluentinc/cp-zookeeper:6.2.0
    # logging:
    #   driver: none
    restart: unless-stopped
    ports:
      - "2181:2181"
      - "2888:2888"
      - "3888:3888"
    volumes:
      - sample_zk_data:/var/lib/zookeeper/data
      - sample_zk_txn_logs:/var/lib/zookeeper/log
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    networks:
      - sample_network

  kafka:
    container_name: sample_kafka
    image: confluentinc/cp-kafka:6.2.0
    # logging:
    #   driver: none
    restart: unless-stopped
    ports:
      - "9092:9092"
    depends_on:
      - zookeeper
    volumes:
      - sample_kafka_data:/var/lib/kafka/data
    environment:
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://localhost:9092
      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: "true"
    networks:
      - sample_network

  zeebe:
    container_name: sample_zb
    image: camunda/zeebe:1.1.0
    environment:
      - ZEEBE_LOG_LEVEL=info
    ports:
      - "26500:26500"
      - "9600:9600"
      - "5701:5701"
    volumes:
      - sample_zeebe_data:/usr/local/zeebe/data
      - ./zeebe-hazelcast-exporter-1.0.0.jar:/usr/local/zeebe/exporters/zeebe-hazelcast-exporter-1.0.0.jar
      - ./application.yaml:/usr/local/zeebe/config/application.yaml
    networks:
      - sample_network

  monitor:
    container_name: sample_zb_monitor
    image: ghcr.io/camunda-community-hub/zeebe-simple-monitor:2.0.0
    environment:
      - zeebe.client.broker.contactPoint=zeebe:26500
      - zeebe.client.worker.hazelcast.connection=zeebe:5701
    volumes:
      - ./simple-monitor-application.yaml:/application.yaml
    ports:
      - "8082:8082"
    depends_on:
      - zeebe
    networks:
      - sample_network