version: '3'
services:
  zipkin:
    image: openzipkin/zipkin
    ports:
      - 9411:9411
  zookeeper:
    # image: wurstmeister/zookeeper
    image: 31z4/zookeeper:3.4.11
  kafka:
    image: wurstmeister/kafka:1.0.1
    depends_on:
      - zookeeper
    links:
      - zookeeper
    ports:
      - 9092:9092
    environment:
      KAFKA_ADVERTISED_HOST_NAME: localhost
      KAFKA_ADVERTISED_PORT: 9092
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_AUTO_CREATE_TOPICS_ENABLE: 'true'
  minio1:
    image: minio/minio
    volumes:
     - volume1:/export
    ports:
     - "9001:9000"
    environment:
     MINIO_ACCESS_KEY: access-key
     MINIO_SECRET_KEY: secret-key
    command: server http://minio{1...4}/export
  minio2:
    image: minio/minio
    volumes:
     - volume2:/export
    ports:
     - "9002:9000"
    environment:
     MINIO_ACCESS_KEY: access-key
     MINIO_SECRET_KEY: secret-key
    command: server http://minio{1...4}/export
  minio3:
    image: minio/minio
    volumes:
     - volume3:/export
    ports:
     - "9003:9000"
    environment:
     MINIO_ACCESS_KEY: access-key
     MINIO_SECRET_KEY: secret-key
    command: server http://minio{1...4}/export
  minio4:
    image: minio/minio
    volumes:
     - volume4:/export
    ports:
     - "9004:9000"
    environment:
     MINIO_ACCESS_KEY: access-key
     MINIO_SECRET_KEY: secret-key
    command: server http://minio{1...4}/export

  ## By default this config uses default local driver,
  ## For custom volumes replace with volume driver configuration.
volumes:
  volume1:
  volume2:
  volume3:
  volume4: