# Confluence with SSL Certificate in a Docker Swarm

# Vladimir Mikhalev
# callvaldemar@gmail.com
# www.heyvaldemar.com

# Configure Traefik and create secrets for storing the passwords on the Docker Swarm manager node before applying the configuration.
# Traefik configuration: https://github.com/heyValdemar/traefik-ssl-certificate-docker-swarm

# Create a secret for storing the password for Confluence database using the command:
# printf "YourPassword" | docker secret create confluence-postgres-password -

# Clear passwords from bash history using the command:
# history -c && history -w

# Run confluence-restore-application-data.sh on the Docker Swarm worker node where the container for backups is running to restore application data if needed.
# Run confluence-restore-database.sh on the Docker Swarm node where the container for backups is running to restore database if needed.
# Run docker stack ps confluence | grep confluence_backups | awk 'NR > 0 {print $4}' on the Docker Swarm manager node to find on which node container for backups is running.

# Deploy Confluence in a Docker Swarm using the command:
# docker stack deploy -c confluence-traefik-ssl-certificate-docker-swarm.yml confluence

version: '3.8'

x-default-opts:
  &default-opts
  logging:
    options:
      max-size: "10m"

networks:
  confluence-network:
    driver: overlay
  traefik-network:
    external: true

volumes:
  confluence-data:
  confluence-postgres:
  confluence-data-backups:
  confluence-postgres-backups:

secrets:
  confluence-postgres-password:
    external: true

services:
  postgres:
    <<: *default-opts
    # Image tag (replace with yours)
    image: postgres:11.11
    volumes:
      - confluence-postgres:/var/lib/postgresql/data
    environment:
      # Database name (replace with yours)
      POSTGRES_DB: confluencedb
      # Database user (replace with yours)
      POSTGRES_USER: confluencedbuser
      POSTGRES_PASSWORD_FILE: /run/secrets/confluence-postgres-password
    networks:
      - confluence-network
    secrets:
      - confluence-postgres-password
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -h 127.0.0.1"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 60s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # Container resources (replace with yours)
      resources:
        limits:
          cpus: '0.55'
          memory: 1G
        reservations:
          cpus: '0.35'
          memory: 512M

  confluence:
    <<: *default-opts
    # Image tag (replace with yours)
    image: atlassian/confluence-server:7.12
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
    environment:
      # Application memory (replace with yours)
      JVM_MINIMUM_MEMORY: 8G
      JVM_MAXIMUM_MEMORY: 8G
      # Confluence URL (replace with yours)
      ATL_PROXY_NAME: confluence.heyvaldemar.net
      ATL_PROXY_PORT: 443
      ATL_TOMCAT_SCHEME: https
      ATL_TOMCAT_SECURE: 'true'
    networks:
      - confluence-network
      - traefik-network
    secrets:
      - confluence-postgres-password
    ports:
      - "8091:8091"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:8090/"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 90s
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # Container resources (replace with yours)
      resources:
        limits:
          cpus: '1.55'
          memory: 10G
        reservations:
          cpus: '0.35'
          memory: 512M
      labels:
        - "traefik.enable=true"
        # Confluence URL (replace with yours)
        - "traefik.http.routers.confluence.rule=Host(`confluence.heyvaldemar.net`)"
        - "traefik.http.routers.confluence.service=confluence"
        - "traefik.http.routers.confluence.entrypoints=websecure"
        - "traefik.http.services.confluence.loadbalancer.server.port=8090"
        - "traefik.http.routers.confluence.tls=true"
        - "traefik.http.services.confluence.loadbalancer.passhostheader=true"
        - "traefik.http.routers.confluence.middlewares=compresstraefik"
        - "traefik.http.middlewares.compresstraefik.compress=true"
    depends_on:
      - postgres

  backups:
    <<: *default-opts
    # Image tag (replace with yours)
    image: postgres:11.11
    # Database backups prune interval (replace with yours). Default is 7 days.
    # find /srv/confluence-postgres/backups -type f -mtime +7 | xargs rm -f

    # Application data backups prune interval (replace with yours). Default is 7 days.
    # find /srv/confluence-application-data/backups -type f -mtime +7 | xargs rm -f

    # Confluence backups interval (replace with yours). Default is 1 day.
    # sleep 24h

    # Run confluence-restore-application-data.sh on the Docker Swarm worker node where the container for backups is running to restore application data if needed.
    # Run confluence-restore-database.sh on the Docker Swarm node where the container for backups is running to restore database if needed.
    # Run docker stack ps confluence | grep confluence_backups | awk 'NR > 0 {print $4}' on the Docker Swarm manager node to find on which node container for backups is running.
    command: sh -c 'sleep 30m
             && while true; do
             PGPASSWORD="$$(cat $$POSTGRES_PASSWORD_FILE)"
             pg_dump
             -h postgres
             -p 5432
             -d confluencedb
             -U confluencedbuser | gzip > /srv/confluence-postgres/backups/confluence-postgres-backup-$$(date "+%Y-%m-%d_%H-%M").gz
             && tar -zcpf /srv/confluence-application-data/backups/confluence-application-data-backup-$$(date "+%Y-%m-%d_%H-%M").tar.gz /var/atlassian/application-data/confluence
             && find /srv/confluence-postgres/backups -type f -mtime +7 | xargs rm -f
             && find /srv/confluence-application-data/backups -type f -mtime +7 | xargs rm -f;
             sleep 24h; done'
    volumes:
      - confluence-data:/var/atlassian/application-data/confluence
      # Application data backups location
      - confluence-data-backups:/srv/confluence-application-data/backups
      # Database backups location
      - confluence-postgres-backups:/srv/confluence-postgres/backups
    environment:
      POSTGRES_PASSWORD_FILE: /run/secrets/confluence-postgres-password
    networks:
      - confluence-network
    secrets:
      - confluence-postgres-password
    deploy:
      mode: replicated
      replicas: 1
      placement:
        constraints:
          - node.role == worker
      # Container resources (replace with yours)
      resources:
        limits:
          cpus: '0.55'
          memory: 1G
        reservations:
          cpus: '0.35'
          memory: 512M
    depends_on:
      - postgres
      - confluence