version: "3"
services:
  nginx-ui:
    image: nginx:alpine
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "4.0"
          memory: 4G
      restart_policy:
        condition: on-failure
        delay: 30s
    ports:
      - 80:80
    networks:
      - webnet
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
      - ./index.html:/etc/nginx/html/index.html
    depends_on:
      - mlflow
      - minio
  mlflow:
    image: mlflow:0.8.2
    environment:
      - MLFLOW_STATIC_PREFIX=/mlflow
      - MLFLOW_S3_ENDPOINT_URL=http://minio:9000/
      - AWS_ACCESS_KEY_ID=minioKey
      - AWS_SECRET_ACCESS_KEY=minioSecret
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 30s
    volumes:
      - mlflow-data:/mlflow_files
    networks:
      - webnet
  minio:
    image: minio/minio:latest
    environment:
      - MINIO_ACCESS_KEY=minioKey
      - MINIO_SECRET_KEY=minioSecret
    deploy:
      replicas: 1
      resources:
        limits:
          cpus: "2.0"
          memory: 2G
      restart_policy:
        condition: on-failure
        delay: 30s
    volumes:
      - minio-data:/data
    networks:
      - webnet
    command: server /data
networks:
  webnet:
volumes:
  mlflow-data:
  minio-data: