### Static Configuration

# Enable dashboard Treafik.
api:
  dashboard: true
  debug: true

# Enable Docker configuration backend
providers:
  file:
    directory: /etc/traefik/dynamic-conf
    watch: true
  docker:
    # If it is in Swarm mode.
    # swarmMode: true
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    # If it is in Swarm mode.
    # network: network_swarm_public
    network: quickstart-traefik2_network_local

# Entrypoints, http and https
# Traefik will listen to incoming request on the port 80/443 (http/https)
entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

# Enable ACME (Let's Encrypt): automatic SSL
certificatesResolvers:
  letsencryptresolver:
    acme:
      # Enable a http challenge named "letsencryptresolver"
      httpChallenge:
        # Tell it to use our predefined entrypoint named "web"
        entryPoint: web
      # The email to provide to let's encrypt
      email: you-email@domain.com
      # Tell to store the certificate on a path under our volume
      storage: /etc/traefik/letsencrypt/acme.json

# Enable Traefik logs(startup, configuration, events, shutdown, and so on)
log:
  level: DEBUG
  format: common
  filePath: /var/log/traefik/traefik.log

# Enable the access logs.
accessLog:
  filePath: /var/log/traefik/access-log
  format: common
