version: "3.3"
##
services:
  swarm-cleaner:
    image: docker
    command: |
      sh -c "
        docker container prune -f &&
        docker image prune -f -a"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
    deploy:
      mode: global
      restart_policy:
#        运行间隔时间设置
        delay: 1h
      resources:
        limits: { cpus: '0.1', memory: '32M' }
        reservations: { cpus: '0.025', memory: '16M' }