---
version: "3.8"
services:
  woodpecker-server:
    image: woodpeckerci/woodpecker-server:latest
    container_name: woodpecker-server
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    networks:
      - woodpecker
      - proxy
    environment:
      - "WOODPECKER_OPEN=true"
      - "WOODPECKER_HOST=${WOODPECKER_URL}"
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
      - "WOODPECKER_ADMIN=${WOODPECKER_ADMIN}"
      - "WOODPECKER_GITEA=true"
      - "WOODPECKER_GITEA_URL=${WOODPECKER_GITEA_URL}"
      - "WOODPECKER_GITEA_CLIENT=${WOODPECKER_GITEA_CLIENT}"
      - "WOODPECKER_GITEA_SECRET=${WOODPECKER_GITEA_SECRET}"
      - "WOODPECKER_GITEA_SKIP_VERIFY=true"
    volumes:
      - "./data:/var/lib/woodpecker"
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.woodpecker.rule=Host(`${WOODPECKER_HOST}`)"
      - "traefik.http.routers.woodpecker.tls=true"
      - "traefik.http.routers.woodpecker.entrypoints=https"
      - "traefik.http.services.woodpecker.loadbalancer.server.port=8000"
  woodpecker-agent:
    container_name: woodpecker-agent
    image: woodpeckerci/woodpecker-agent:latest
    restart: unless-stopped
    cpus: 0.5
    mem_limit: 512m
    depends_on:
      - woodpecker-server
    networks:
      - woodpecker
    environment:
      - "WOODPECKER_SERVER=woodpecker-server:9000"
      - "WOODPECKER_AGENT_SECRET=${WOODPECKER_AGENT_SECRET}"
    volumes:
      - "/var/run/docker.sock:/var/run/docker.sock"
networks:
  woodpecker:
  proxy:
    external: true
