version: '2'

services:
  jekyll:
    image: jekyll/jekyll:latest
    command: jekyll serve --watch --force_polling --verbose
    ports:
      - 4000:4000
    volumes:
    # eg. https://github.com/Bloc/portfolio-iro/
      - .:/srv/jekyll
