version: "3"

#https://github.com/Akaame/kafdrop-demo/blob/master/docker-compose.yml

networks:
    appnetwork:

services:
    zookeeper:
        image: confluentinc/cp-zookeeper
        hostname: zookeeper
        ports:
            - "2181:2181"
        environment: 
            ZOOKEEPER_CLIENT_PORT: 2181 
        networks:
            - appnetwork
    
    kafka:
        image: confluentinc/cp-kafka
        hostname: kafka
        depends_on: 
            - zookeeper
        ports:
            - "9092:9092"
        environment:
            KAFKA_BROKER_ID: 1
            KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
            KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: PLAINTEXT:PLAINTEXT,HOST:PLAINTEXT
            KAFKA_INTER_BROKER_LISTENER_NAME: PLAINTEXT
            KAFKA_ADVERTISED_LISTENERS: PLAINTEXT://kafka:29092,HOST://localhost:9092
            KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
        networks: 
            - appnetwork

    kafdrop:
        image: obsidiandynamics/kafdrop
        ports:
            - "9000:9000"
        depends_on: 
            - kafka
        networks: 
            - appnetwork
        environment: 
            KAFKA_BROKERCONNECT: kafka:29092
            SERVER_SERVLET_CONTEXTPATH: "/"