version: '3'
services:
  kibana:   
    hostname: opendistroforelasticsearch-kibana-test
    image: amazon/opendistro-for-elasticsearch-kibana:1.1.0
    ports:
      - 5603:5601
    networks: [opendistroforelasticsearch]
    environment:
      ELASTICSEARCH_HOSTS: https://elasticsearch:10200

    # Configure certificate and key files to enable SSL. The certificate
    # provided in the example is self-signed, and thus insecure. It should
    # only be used for experimentation, never in production.
    #
    # environment:
    #   - SERVER_SSL_CERT=/usr/share/kibana/config/opendistroforelasticsearch.example.org.crt
    #   - SERVER_SSL_KEY=/usr/share/kibana/config/opendistroforelasticsearch.example.org.key

  elasticsearch:
    hostname: opendistroforelasticsearch
    image: amazon/opendistro-for-elasticsearch:1.1.0
    networks: [opendistroforelasticsearch]
    environment:
      - discovery.type=single-node
    ports:
      - 10200:9200
      - 10600:9600 # required for Performance Analyzer
networks:
  opendistroforelasticsearch:
  

#curl -XGET https://192.168.9.26:6200/_cat/indices?v -u admin:admin --insecure
#curl -XGET https://192.168.9.26:9200/_cat/nodes?v -u admin:admin --insecure
#curl -XGET https://192.168.9.26:9200/_cat/plugins?v -u admin:admin --insecure
#curl -XPUT 'https://192.168.9.26:9200/logtest?pretty' -u admin:admin --insecure

#admin/admin