
[http]
    [http.middlewares]
         [http.middlewares.https-redirect.redirectscheme]
              scheme = "https"
              permanent = true
         [http.middlewares.security-headers.headers]
              # CORS
              AccessControlAllowMethods = ["GET", "OPTIONS", "PUT"]
              AccessControlAllowOrigin = "origin-list-or-null"
              AccessControlMaxAge = 100
              #AddVaryHeader = true
              BrowserXssFilter = true
              ContentTypeNosniff = true
              ForceSTSHeader = true
              FrameDeny = true
              SSLRedirect = true
              STSIncludeSubdomains = true
              STSPreload = true
              ContentSecurityPolicy = "default-src 'self' 'unsafe-inline'"
              CustomFrameOptionsValue = "SAMEORIGIN"
              ReferrerPolicy = "same-origin"
              FeaturePolicy = "vibrate 'self'"
              STSSeconds = 315360000