version: '3.7'

configs:
  mysql_config:
    external: true

services:
  mysql-master:
    image: 'bitnami/mysql:5.7'
    ports:
      - '3309:3306'
    volumes:
      - mysql_data:/bitnami/mysql/data
    environment:
      - MYSQL_REPLICATION_MODE=master
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_ROOT_PASSWORD=root_password
      - MYSQL_USER=my_user
      - MYSQL_PASSWORD=my_password
      - MYSQL_DATABASE=my_database
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.db-node == true]  # 部署标签约束
    configs:
      - source: mysql_config
        target: /opt/bitnami/mysql/conf/my_custom.cnf
  mysql-slave:
    image: 'bitnami/mysql:5.7'
    ports:
      - '3308:3306'
    depends_on:
      - mysql-master
    environment:
      - MYSQL_REPLICATION_MODE=slave
      - MYSQL_REPLICATION_USER=repl_user
      - MYSQL_REPLICATION_PASSWORD=repl_password
      - MYSQL_MASTER_HOST=mysql-master
      - MYSQL_MASTER_PORT_NUMBER=3306
      - MYSQL_MASTER_ROOT_PASSWORD=root_password
    volumes:
      - mysql_data1:/bitnami/mysql/data
    deploy:
      mode: replicated
      replicas: 1
      placement:
        # constraints: [node.labels.pm-node == true]  # 部署标签约束
        constraints: [node.labels.db-node == true]  # 部署标签约束
    configs:
      - source: mysql_config
        target: /opt/bitnami/mysql/conf/my_custom.cnf   
        
volumes:
  mysql_data:
  mysql_data1: