services:
  db:
    image: mysql:5.7
    restart: always
    ports:
      - 3306:3306
    environment:
      MYSQL_DATABASE: test
      MYSQL_ROOT_PASSWORD: password
      MYSQL_USER: demo
      MYSQL_PASSWORD: demo
    volumes:
      - mysql_data:/var/lib/mysql

volumes:
  mysql_data: {}
