version: '3'
# author:David.che
services:

  opensearch-1:
    image: opensearchproject/opensearch
    container_name: opensearch-1
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9200"]
      interval: 15s
      timeout: 10s
      retries: 3
    restart: unless-stopped
    ports:
      - "9200:9200"
      - "9300:9300"
      - "9600:9600"
    environment:
      - "OPENSEARCH_JAVA_OPTS=-Xms1g -Xmx1g"
      - "network.host=0.0.0.0"
      - "http.port=9200"
      - "transport.port=9300"
      - "discovery.type=single-node"
      - "bootstrap.memory_lock=true"
      - opendistro_security.disabled=true
    volumes:
      - search-data:/usr/share/opensearch/data
    networks:
      - search-net
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536
        hard: 65536
    cap_add:
      - IPC_LOCK

  opensearch-dashboards:
    image: cheshuai/opensearch-dashboards:1.0.0-beta1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      OPENSEARCH_HOSTS: http://opensearch-1:9200
    networks:
      - search-net

volumes:
  search-data:

networks:
  search-net:

