version: '3'
# https://github.com/hhko/Learning/blob/58c5cc7216d96e851f984b08134c20728089ad0c/1.Tutorials/OpenSearch/Elastic_Beat_%EA%B0%9C%EB%B0%9C_%ED%99%98%EA%B2%BD_%EB%A7%8C%EB%93%A4%EA%B8%B0_by_Docker.md
services:
  opensearch-node1:
    # image: opensearchproject/opensearch:1.0.0-beta1
    image: cheshuai/opensearch:1.0.0-beta1
    container_name: opensearch-node1
    environment:
      - discovery.type=single-node
      - cluster.name=opensearch-cluster
      - node.name=opensearch-node1
      # - discovery.seed_hosts=opensearch-node1,opensearch-node2
      # - cluster.initial_master_nodes=opensearch-node1,opensearch-node2
      - bootstrap.memory_lock=true # along with the memlock settings below, disables swapping
      - "OPENSEARCH_JAVA_OPTS=-Xms512m -Xmx512m" # minimum and maximum Java heap size, recommend setting both to 50% of system RAM
    ulimits:
      memlock:
        soft: -1
        hard: -1
      nofile:
        soft: 65536 # maximum number of open files for the OpenSearch user, set to at least 65536 on modern systems
        hard: 65536
    volumes:
      - opensearch-data1:/usr/share/opensearch/data
    ports:
      - 9200:9200
      - 9600:9600 # required for Performance Analyzer
    networks:
      - opensearch-net
  opensearch-dashboards:
    # image: opensearchproject/opensearch-dashboards:1.0.0-beta1
    image: cheshuai/opensearch-dashboards:1.0.0-beta1
    container_name: opensearch-dashboards
    ports:
      - 5601:5601
    expose:
      - "5601"
    environment:
      # OPENSEARCH_URL: http://opensearch-node1:9200
      OPENSEARCH_HOSTS: http://opensearch-node1:9200
    networks:
      - opensearch-net

volumes:
  opensearch-data1:

networks:
  opensearch-net: